require("core.options")
require("plugins.plugins-setup")
require("core.keymaps")

-- 插件
require("plugins.nvim-tree")
require("plugins/treesitter")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/mason")
require("plugins/color")
require("plugins/lualine")
require("plugins/indentscope")
require("plugins/lsp-lua")
